### ISSUE TITLE
make faild

### ISSUE THREAD

**Issue by Sjey-Lyn** [SurfaceMan/surface_match#1]
![Screenshot from 2022-11-23 16-23-53](https://user-images.githubusercontent.com/74102271/203500502-8d7d24f0-bf69-4e6d-9555-32798fca7219.png)
why make stuck in ppf.cpp?

**Comment by TheodoroCardoso** [comment]
The result on the README image look very promising!
I'd like to give it a test, however I've got the exact same problem as above after executing the following commands:
```
git clone https://github.com/SurfaceMan/surface_match.git --recurse-submodules 
cd surface_match/
mkdir build
cd build
cmake ..
make
```
Is there any reason for that @SurfaceMan?
Any help would be appreciated.

**Comment by SurfaceMan** [comment]
> The result on the README image look very promising! I'd like to give it a test, however I've got the exact same problem as above after executing the following commands on ubuntu 20.04:
> 
> ```
> git clone https://github.com/SurfaceMan/surface_match.git --recurse-submodules 
> cd surface_match/
> mkdir build
> cd build
> cmake ..
> make
> ```
> 
> Is there any reason for that @SurfaceMan? Any help would be appreciated.

Can you provide your system information, like  sytem edition、gcc version...

**Comment by TheodoroCardoso** [comment]
> > The result on the README image look very promising! I'd like to give it a test, however I've got the exact same problem as above after executing the following commands on ubuntu 20.04:
> > ```
> > git clone https://github.com/SurfaceMan/surface_match.git --recurse-submodules 
> > cd surface_match/
> > mkdir build
> > cd build
> > cmake ..
> > make
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is there any reason for that @SurfaceMan? Any help would be appreciated.
> 
> Can you provide your system information, like sytem edition、gcc version...

Ubuntu Focal 20.04
gcc 9.4

```
theodoro@ubuntu:~ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

**Comment by SurfaceMan** [comment]
![1](https://user-images.githubusercontent.com/114746178/213179739-8d5596ba-493a-4f85-8b72-d923e69b59e6.png)
try delete -Wa flag

**Comment by SurfaceMan** [comment]
finshed
