### ISSUE TITLE
icp distance_the

### ISSUE THREAD

**Issue by fanyunchao** [SurfaceMan/surface_match#5]
findClosestPoint返回的距离的平方，在findCorresponds过程中（icp.cpp-133行），设定的距离阈值存在平方的差异

**Comment by SurfaceMan** [comment]
感谢，这个问题已修复[c49e74d](https://github.com/SurfaceMan/surface_match/commit/c49e74d0b1c18867cba2c32991eef427b662b781)

**Comment by SurfaceMan** [comment]
fixed
