### ISSUE TITLE
Ask for some question.(ICP,  Multi-Model, Scale)

### ISSUE THREAD

**Issue by XiaXingLuo** [SurfaceMan/surface_match#8]
@SurfaceMan     
Thanks for your excellent work again.There are some problems I want to communicate with you.     
    
1: I want to evaluate the matching result.     
I noticed that the code use ICP, line 190-192 in the icp.cpp, the method of calculating mse is different from puplic formula of MSE, does it have particular meaning now in the code? In order to evaluate the matching precision, I use your project with puplic MSE formula to calculate RMSE, the result is beyond on 2 millimetre, the result is a little bad, I don't know whether I use wrong way.I think of use the output of  the project and use ICP algorithm with PCL library, it will increase the time,so I haven't tried it.      
  
2: Do you have good idea of multi-model matching or will you support the function.   
Now, your project performs well when one single model, scene have one or more object.However, there are many different shape object in scene, we need multi-model to match. I have a stupid idea using every model to detect the scene. Do you have good idea about it.?     
     
3:Dose ppf methods fit for multi-view or multi scale 3D object recognition?    
Multi-view I means the object has the same shape as model, such as right triangle and obtuse triangle.         
Multi-scale I means the object has different size from model, such as different diamater circle.

**Comment by XiaXingLuo** [comment]
> @XiaXingLuo 1.1 Line 190-192 in the icp.cpp means L2 distence average. "mse" should renamed as "avgDistance". 1.2 Matching precision depend on model size, noise, visible area, point cloud quality 1.3 Your question inspire me that distance may not a good judgment for iteration in icp, we want higher score, why not use score directly
> 
> 2.1 For multi-model matching, I agree with you. So there's no plan to support that. 2.2 To decrese time cost, it's a good idea to find small range point cloud to do ppf-matching. less scene point, match faster. Like cut background if at fix position, use object detection in 2D image then project to 3D space
> 
> 3.1 ppf only support rigid object, size must be same for model and target in scene 3.2 What you mean multi-view, deformation? If true, ppf can't handle it.

Thanks for your reply.
1.1 Get it! ,I did test, the results of "avgDistance" and MSE  are not much different in match score, but have a little difference in rotation matrix, leading difference matching effects visually.

1.3 Use higher score to evaluate the matching result is false propositions in my view. I don't know the ground truth.Higher score result only exists in one test, only using score doesn't convince other people, most people may would rather use specific number of precision than score.But it seems that there is no good idea to evaluate the matching result, even though known ICP, the fitness score only provides references.What's more, in other paper on 3D matching include non-rigid and rigid also use time and RMSE to  compare and evaluate, and the value of RMSE is about 5 millimeter.

2.2-2.2 I will try it with your valuable advice.

3.1-3.2 Yeah,I means deformation.There is high-speed template matching algorithm based on shape-based multi-target and multi-angle algorithm in Halcon, but it seems only to fit for image detection not for 3D.

**Comment by SurfaceMan** [comment]
@XiaXingLuo 
Halcon :[deformable surface-based](https://www.mvtec.com/doc/halcon/13/en/toc_3dmatching_deformablesurfacebased.html)

**Comment by XiaXingLuo** [comment]
> @XiaXingLuo Halcon :[deformable surface-based match](https://www.mvtec.com/doc/halcon/13/en/toc_3dmatching_deformablesurfacebased.html)

Thanks.I got it. This is commercial tools. I just don't know how they achieve the algorithm, maybe I should do more research.
