### ISSUE TITLE
The implement of edge point in TODO.md

### ISSUE THREAD

**Issue by jiangzhiwei2018** [SurfaceMan/surface_match#9]
I notice that the 7th item “edge point“ in `TODO.md`, and I'm interested in that.

I had tried the PCL to extract edge point as the `ppf::Dectector ` input but didn't get the well results.

So, maybe I need to implement `edge point` extraction in the main `pff.cpp`.

 could you inform me more implement's details about `edge point`  or paper?

**Comment by SurfaceMan** [comment]
1. papers: 
3D Object Detection and Localization using Multimodal Point Pair Features. DOI: 10.1109/3dimpvt.2012.53
Point Pair Feature-Based Pose Estimation with Multiple Edge Appearance Models (PPF-MEAM) for Robotic Bin Picking. DOI: 10.3390/s18082719
2. The "edge point" is just small part of whole point cloud, so it should be sampled more dense than original ppf.

**Comment by jiangzhiwei2018** [comment]
Thanks.
